name: Frontend Code Format Check
on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm ci
      - name: Run Prettier Check
        run: npx prettier --check .
      - name: Run ESLint Check
        run: npx eslint .
